# Generated by Django 5.1.3 on 2024-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("budget", "Budget"),
                ],
                max_length=20,
            ),
        ),
    ]
