# Generated by Django 5.1.3 on 2024-11-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_category_is_custom_alter_category_category_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("payment_method", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
