# Generated by Django 5.1.3 on 2024-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="status",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(default="income", max_length=50),
        ),
    ]
