# Generated by Django 5.1.3 on 2024-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")], max_length=50
            ),
        ),
    ]
